### ISSUE TITLE
mDNS & OTA Failing

### ISSUE THREAD

**Issue by asantaga** [OttoWinter/esphomeyaml#101]
Hey all,

I know Im logging this with "two" issues but I think they are related.. 

If I push a esphomeyaml to my esp8266 Im noticing that the mdns name isnt being resolved AND OTA does appear to work

1. mDNS just isnt working, if i ping alarmsensor.local i get nothing, but if I push a custom (not esphomeyaml) sketch with mDNS enabled it works. I can ping the esp8266 using the real IP address however....

2. Same for OTA,  just doesnt work in this scenario I am able to get a custom sketch working fine but with esphomeyaml it doesnt work. Withn the ESP8266 I get a message saying OTA Begin : Error   (dont have the precise error message here).

Any clues to debugging this? Given there are so few issues on ota im guessing this is something else

**Comment by OttoWinter** [comment]
In my experience OTA itself is very robust. What however is a problem quite often is WiFi and maintaining a network connection (still have no idea why this seems to be so hard). I think the best place to find out more about this is by looking at the USB/UART logs.

**Comment by flozsc** [comment]
Having similar issues. Interestingly, when pinging sensorname.local from my Mac it works. But the Hassio add-on apparently cannot resolve it. Is there a possible issue with mDNS?

I worked around it by assigning manual IP addresses; this way esphomeyaml will just connect via IP for OTA updates.

**Comment by OttoWinter** [comment]
@flozsc Each network is different, and usually this is an issue with the network configuration. All esphomelib does is:

 * a) Broadcast the node's presence using mDNS. Done by the WiFi stack
 * b) Resolve the node's IP address using network's hostname resolver. Done by the HassIO operating system.

All of these things are done by components that esphomelib doesn't have access to, so the work-around is, and will only be to set a static IP address.

**Comment by OttoWinter** [comment]
In 1.9, esphomeyaml will suggest you to use static IPs if the name resolution fails.
