### ISSUE TITLE
[Feature Request] HASS-Style password/secrets separation

### ISSUE THREAD

**Issue by pyrosmiley** [OttoWinter/esphomeyaml#103]
Since it's my understanding that esphomeyaml interprets YAML into compilable C code, I wouldn't imagine this would be a particular resource strain, hardware-wise. In fact, it may already be possible and I just haven't figured it out?

In HA, I've made my `configuration.yaml` file more secure and shareable by putting all my passwords/API keys/tokens/etc in `secrets.yaml` as per [the docs here](https://www.home-assistant.io/docs/configuration/secrets/). I'd like to be able to do that with EHY for a few reasons:

1. Can backup to github without exposing intimate details about my wifi network and passwords
2. Easier to share configs with others for help or debugging purposes
3. In a more advanced use case, it'd make having many devices much more manageable -- for example, I now have 4 (soon to be up to 8!) ESPs flashed with this firmware, and they're all set with static IPs for better network management and battery life. Being able to have the assigned IPs in one file would make reference MUCH easier! And if I make any changes to the wifi network, I can update sensitive values once and have it apply to all of the devices at compile time.

This may be one of those things where I am one of like, two people in the world that wants this, in which case I totally understand if implementing this ability would take a lot of work. It would just be nice is all

**Comment by OttoWinter** [comment]
https://esphomelib.com/esphomeyaml/guides/faq.html#tips-for-using-esphomeyaml 😉

**Comment by pyrosmiley** [comment]
Welp! Don’t know how I missed that but I did. Much appreciated!
