### ISSUE TITLE
[Feature Request] Separate state message for Deep Sleep instead of last will

### ISSUE THREAD

**Issue by pyrosmiley** [OttoWinter/esphomeyaml#105]
I tried to look around the C to see if it was possible, and it may not be. I know this one's a long shot, but it would be really nice to be able to tell Home Assistant the difference between the node being "actually dead" and "just asleep". I know it's possible to send custom `birth` and `will` messages, but I'm hoping there's a way to have a third option, or even just a way to automate a custom MQTT message right as it's preparing for deep sleep.

Thanks so much!!!!!!

**Comment by OttoWinter** [comment]
I added an `shutdown_message` for the next release. There you will be able to specify what to publish if the node is shutting down safely.

**Comment by pyrosmiley** [comment]
Wonderful, thanks so much!
