### ISSUE TITLE
Limit upload speed

### ISSUE THREAD

**Issue by fabaff** [OttoWinter/esphomeyaml#121]
After I published a [blog post](https://fabian-affolter.ch/blog/wetter-station-mit-e-ink-display-in-5-min/) about a simple "weather station" some people got back to me about the serial upload speed. They were not able to flash their devices. 

Not all ESP32 devices are able to handle a baudrate of 921600 for the upload. 921600 seems to be the default speed used by Platform.io. I have two ESP32 dev boards where i can reproduce the issue and a lower speed allows me to flash them successfully (at least while using them directly in Platform.io with `upload_speed=115200` in `platformio.ini`).

One option would be to make the upload baudrate configurable or lower it by default. The impact on the consumed time seems irrelevant as we are talking about seconds and not minutes.

**Comment by OttoWinter** [comment]
Huh, platformio must have changed that at some point. I think setting the speed to 115200 globally is not a problem, since I think most uploads happen over OTA anyway. And I'm too lazy to create another option to increase it manually :) The `esphomeyaml:` section in the configuration is already crowded enough :)

**Comment by rlust** [comment]
On the first load of a new ESP32 I am able to upload via serial, but further uploads will not got either serial , I get the following error every time.
A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x1B)
*** [upload] Error 2
Is this the same issue?

**Comment by fabaff** [comment]
> Is this the same issue?

@rlust, yes.

**Comment by fabaff** [comment]
#122 works like a charm. Thanks.
