### ISSUE TITLE
Error during serial upload

### ISSUE THREAD

**Issue by rlust** [OttoWinter/esphomeyaml#140]
I have an ESP32 that I loaded initially via my MAC via serial, now when trying to burn updated firmware via serial I am getting the following error:
Sometimes I am able to get OTA to working by using --upload-port ip.

`Retrieving maximum program size .pioenvs/displaywave32/firmware.elf
Checking size .pioenvs/displaywave32/firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [=         ]  14.3% (used 46808 bytes from 327680 bytes)
PROGRAM: [======    ]  63.9% (used 837900 bytes from 1310720 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, esptool, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/cu.SLAB_USBtoUART
Uploading .pioenvs/displaywave32/firmware.bin
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_____....._____....._____....._
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse
MAC: b4:e6:2d:87:17:d5
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0xffffff, SizeID=0xff), defaulting to 4MB
Compressed 15088 bytes to 9755...

A fatal error occurred: Timed out waiting for packet content
*** [upload] Error 2
`

**Comment by OttoWinter** [comment]
Sorry, can't help there. It's probably an error with your board *or* it might be because the upload speed is too high. Could you verify you're running esphomeyaml > v1.8.1? `esphomeyaml . version`
