### ISSUE TITLE
MQTT Default Topic

### ISSUE THREAD

**Issue by bachoo786** [OttoWinter/esphomeyaml#146]
Hi 

Thank you for this application. 

I want to know what is the default MQTT topic. At the  moment all my sensors connect to HA via auto discovery mqtt enabled. But I want to know the topic so I can subscribe to it on my phone.

Thanks.

**Comment by brandond** [comment]
See: https://esphomelib.com/esphomeyaml/components/mqtt.html#defaults

**Comment by bachoo786** [comment]
So my current topic is my nkde name and Mac address of my nodemcu? E.g. nodemcu/xx:xx:xx:xx:xx ?

And to change the topic I need to add in my nodemcu.yaml configuration file the following:

mqtt:
      topic: myown/topic
