### ISSUE TITLE
Template switch is spamming its state

### ISSUE THREAD

**Issue by frog32** [OttoWinter/esphomeyaml#155]
I have a template switch with the following definition and this publishes its state multiple times a second. When I subscribe to its mqtt topics I get the this output:

coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF
coffee_machine/switch/coffee_machine/state OFF

```
switch:
  - platform: template
    name: "Coffee Machine"
    icon: "mdi:coffee"
    lambda: >-
      if (id(power_led).value) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on:
          id: power_btn
      - delay: 2s
      - switch.turn_off:
          id: power_btn
    turn_off_action:
      - switch.turn_on:
          id: power_btn
      - delay: 2s
      - switch.turn_off:
          id: power_btn
```

**Comment by OttoWinter** [comment]
Ah yes, missed that when refactoring the core switch code.
