### ISSUE TITLE
Configuration version / checksum

### ISSUE THREAD

**Issue by brandond** [OttoWinter/esphomeyaml#156]
It'd be nice if there was a way to confirm that a node is running the latest build of its firmware. Perhaps some sort of hash of the configuration YAML + library versions that could be embedded in the firmware at build time, and compared to the current project environment? Even a build timestamp would be a good start.

**Comment by OttoWinter** [comment]
I've already done exactly that :)

Just waiting for Home Assistant v0.81.0 to drop to get the new device registry view. There you will be able to view both of those things. I'll see if I can backport those changes to show the esphomelib version + build time in the logs too.

It would look like this:

<img width="317" alt="screen shot 2018-10-09 at 18 55 43" src="https://user-images.githubusercontent.com/6833237/46685137-01a7cb80-cbf5-11e8-84af-d4a7ab18d9dc.png">

(build time of the firmware version will also be displayed, just missing from this screenshot)
