### ISSUE TITLE
hlw8012 is sending out negative values

### ISSUE THREAD

**Issue by pschmitt** [OttoWinter/esphomeyaml#163]
I don't if you got your Sonoff POW yet but mine only reads negative values:

```
sonoff_pow/debug [D][sensor.hlw8012:059]: Got power=-5.2W, current=-0.1A
```
I don't believe this is intended since Home Assistant does not seem to like these (they are "rounded" to 0). Anyway this is easily fixable with a filter (`lambda: return fabs(x);`) - just wanted to let you know.

[The config I used](https://github.com/pschmitt/esphomeyaml-config/blob/e8b4c841f62fdcd4204ce9d17f373336b48fe525/config/sonoff_pow.yaml)

**Comment by OttoWinter** [comment]
Thank you! No, I don't have a Sonoff POW, as getting the whole test setup working would take time than writing the code :D Most of the time (prob. 60%) new integrations work from the start :) I forgot to add the warning I usually write for such integrations in the docs.
