### ISSUE TITLE
No way to handle upgraded ESP board ??

### ISSUE THREAD

**Issue by vincegre** [OttoWinter/esphomeyaml#205]
After having checked documentation as best as I could, it looks like there is no way to indicate specific flash size :( How can I handle ESP boards that have been flash upgraded ? I have done that on my Sonoff so they can support OTA but i see no way in esphomeyaml to indicate that extra memory so it can be flashed correctly !
Did I miss something obvious ? :/

Vincèn

**Comment by OttoWinter** [comment]
Closing this issue as we found a good solution in discord. For reference, you can open the `<NODE_NAME>/platformio.ini` file and use one of these options: http://docs.platformio.org/en/latest/platforms/espressif8266.html#flash-size
