### ISSUE TITLE
Please add support for ESP03 board.

### ISSUE THREAD

**Issue by horga83** [OttoWinter/esphomeyaml#211]
**Is your feature request related to a problem? Please describe.**

Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Please add support for ESP03 board.

**Additional context**
The ESP03 board which is an esp8266 has additional I/O and is far more usefull than the esp01 boards for many  things.

**Comment by brandond** [comment]
@horga83 it's already supported, just use `board: esp01_1m`. I have a half dozen or so of these and they're working great.
