### ISSUE TITLE
RGB+W light in which RGB part is based on fastled output

### ISSUE THREAD

**Issue by wuub** [OttoWinter/esphomeyaml#264]
It's simple actually. I built a lamp in which RGB part is based on individually addressable LED's, and WW part is standard led strip with PWM dimming. 

It would be good to have it as a single, autodiscovered component in HA instead of two separate lights.

**Is your feature request related to a problem? Please describe.**
Not really, I can hack this up by using fastled_spi light + separate monochromatic light and configure appropriate MQTT Light on HA side. 

**Describe the solution you'd like**
To somehow create a fastled_spi *output* and attach it to normal RGBW light?

**Additional context**
n/a

**Comment by OttoWinter** [comment]
I don't this is worthy of a component. And also it would definitely not work well with the light architecture. A `LightState` object has exactly one `LightOutput`.

Similar feature: https://github.com/OttoWinter/esphomelib/pull/147

**Comment by wuub** [comment]
sure thing. makes sense. I'll just disable discovery and configure mqtt light myself on home-assistants side.
