### ISSUE TITLE
Support ESP8285

### ISSUE THREAD

**Issue by HydrelioxGitHub** [OttoWinter/esphomeyaml#31]
I realized that some Arilux devices run on ESP8285 (like my Arilux AL-LC03) and not on ESP8266. Is there any support on the roadmap ?

**Comment by OttoWinter** [comment]
ESP8285s are pretty much equivalent to ESP8266s and AFAIK work without any additional setup when the board is set to `esp01_1m`. At least my Sonoff 4CH (which is also based on the ESP8285 has been working fine so far (https://esphomelib.com/esphomeyaml/devices/sonoff_4ch.html#step-3-creating-firmware)
