### ISSUE TITLE
Shows as offline, but is online

### ISSUE THREAD

**Issue by olskar** [OttoWinter/esphomeyaml#324]
![screenshot_20190111-184626](https://user-images.githubusercontent.com/18314560/51050511-55012f80-15d1-11e9-84f3-369f63a4265f.jpg)

Updated a nodemcu to latest version. Now in dash board it shows as offline but i can still se message coming in in debug

**Comment by dreed47** [comment]
I also get this using the latest beta

**Comment by olskar** [comment]
Could this be related to mdns which I am having troubles with. It does not
find bastu.local, but if I change the settings to a static IP it says
online.

Den fre 11 jan. 2019 kl 19:07 skrev dreed47 <notifications@github.com>:

**Comment by OttoWinter** [comment]
Internally, just `ping <HOSTNAME>.local` is called (or `ping <STATIC_IP>` if configured). So this is related to https://github.com/OttoWinter/esphomeyaml/issues/315

**Comment by olskar** [comment]
Makes sense, closing this @OttoWinter and hopes for a solution in #315
