### ISSUE TITLE
Wrong password in main.cpp

### ISSUE THREAD

**Issue by itProfi** [OttoWinter/esphomeyaml#350]
In version 1.10.1 - i have password for my AP - "20182018."
![16-01-2019 211349](https://user-images.githubusercontent.com/6728198/51269482-afd0c780-19d3-11e9-9fde-169b619fc8d9.jpg)

In main.cpp after compile it we have! -"20182018.0" !
I try reproduce it 5 times afer delete all libs, same effect!

**Comment by brandond** [comment]
You probably need to quote the password in your YAML file - the parser is treating it as a number instead of a string because it is numeric and unquoted. This is standard YAML behavior.

**Comment by OttoWinter** [comment]
Yes this is how YAML works. If you type in something like `42.` it will get converted to the _number_ `42.0` and the information about how it was typed in originally is lost. You have to put quotes around these values in YAML
