### ISSUE TITLE
Typo in oversampling 32x

### ISSUE THREAD

**Issue by mystcat** [OttoWinter/esphomeyaml#3556]
https://github.com/esphome/esphome/blob/8998c5f6dd5291c0bfb881dda4068627a51e037a/esphome/components/bmp3xx/sensor.py#L28

There is a typo in sensor.py making it impossible to set oversampling to 32x. It must be uppercase as other values in the list.

**Comment by martgras** [comment]
Please don't open issues here
For issues, please go to [the issue tracker](https://github.com/esphome/issues/issues).

Nevertheless I opened a PR for it
https://github.com/esphome/esphome/pull/3559
