### ISSUE TITLE
New PMS5003T

### ISSUE THREAD

**Issue by Stef-90** [OttoWinter/esphomeyaml#4088]
https://github.com/esphome/esphome/blob/39c6c2417ac2b3b20f4dbc2457aa380b330a7fb9/esphome/components/pmsx003/sensor.py#L57

I got few pms5003T and they have pm1, pm2.5 and pm10 as well as temp humidity etc....

Using type pmsX003 I lose temp/humidity, but pm values match my other pms5003 side by side....
When using type pms5003T I only get pm2.5 so I tried using type pms5003ST but this new T revision doesn't have formaldehyde( i checked the code it's at length 28, so it throws errors.

Could you please add support for the new T type

**Comment by grillp** [comment]
You are not supposed to post issues here.

see: https://github.com/esphome/esphome/issues/430
