### ISSUE TITLE
Feature Request: make build output path configurable

### ISSUE THREAD

**Issue by jansepke** [OttoWinter/esphomeyaml#49]
It would be nice to have the build output path configurable, so one can put all build output folders in a seperate folder, to streamline folder structure. this would also help ignoring the build output folders in gitignore files.

current situation:
- smart-home
|- livingroom.yaml
|- livingroom

would like to change it to:
- smart-home
|- livingroom.yaml
|- build
|-- livingroom

I think these would need another config property and changes to these method:
https://github.com/OttoWinter/esphomeyaml/blob/a04438e92434fcc472ebfce5a1d923630ec012c6/esphomeyaml/__main__.py#L27

**Comment by brandond** [comment]
I'd love to see something like this too - right now I have completely separate copies of all the .piolibdeps etc for each of my half-dozen nodes.

**Comment by OttoWinter** [comment]
Messed up the commit name, but here you go: https://github.com/OttoWinter/esphomeyaml/commit/6ae8e3495f7df3c0937bc48bea8395cb07e83123 :P
