### ISSUE TITLE
Templated types aren't allowed in script parameters.

### ISSUE THREAD

**Issue by AlmostInteractive** [OttoWinter/esphomeyaml#6970]
https://github.com/esphome/esphome/blob/1e05bcaa614040617ef94340a54ca3f22871c4ac/esphome/components/script/__init__.py#L91

The allowed character list doesn't include "<>" so templated types, like `std::vector<int>` aren't allowed as parameters in a script.

**Comment by unic8s** [comment]
Hi @AlmostInteractive this repo is not meant for posting issues. I'm pretty sure it will be closed soon.
You should use this repo https://github.com/esphome/issues instead.

Have a great day!

**Comment by ssieb** [comment]
To avoid future confusion, the last comment was correct, but the issue was moved to the right location after.

**Comment by ssieb** [comment]
Try the linked PR.
