### ISSUE TITLE
cant choose usb for upload

### ISSUE THREAD

**Issue by mefizto** [OttoWinter/esphomeyaml#80]
there is no thingy for choosing how to upload the firmware if i hit upload is trying to do OTA but cant choose to upload firmware via USB, also there is no validate option.
<a href="https://i.imgur.com/6L6hYpZ.png">
  <img src="https://imgur.com/6L6hYpZl.png" />
</a>

**Comment by stefball** [comment]
If I remove and replug the cable in the USB port, the connection to serial port appears.

**Comment by mefizto** [comment]
thank you stefball and zmrow

i already tried using different ports and different modules with no results, i can upload a firmware via arduino IDE.

I tried uploading the webupdate sketch and then upload the bin firmware but didn't work.

Next im going to try from Espeasy and then upload the esphomeyaml firmware. But it will be nice if i can just upload from USB, so i appreciate if you have more comments about it.

**Comment by stefball** [comment]
The cable I used was directly connected to a port of a Raspberry 3 where I installed hassio.

**Comment by mefizto** [comment]
i tried different ports and still can't choose the port

**Comment by mefizto** [comment]
i finally use ESPeasy to upload the firmaware, it never showed me the option to upload to usb, none of the 4 ports of the raspberry worked, but I know that the ports work correctly

**Comment by brandond** [comment]
Are you sure the Pi's USB ports are supplying sufficient power to the ESP32? If you're using it with an underpowered supply then it may power up enough to light the LEDs on the board, but not enough to actually operate either the ESP chip or the usb-serial converter that's built into the dev boards.

**Comment by mefizto** [comment]
Sorry i was using the edge version of the add-on, I change to stable version and everything went fine.
